# Generated by Django 5.2.3 on 2025-08-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_myuser_last_seen_group_groupmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
    ]
