# Generated by Django 5.2.3 on 2025-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="visible_to_receiver",
            field=models.BooleanField(default=True),
        ),
    ]
