# Generated by Django 5.2.3 on 2025-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_message_visible_to_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
