# Generated by Django 5.2.3 on 2025-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_block_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="visible_to_sender",
            field=models.BooleanField(default=True),
        ),
    ]
