# Generated by Django 5.2.3 on 2025-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_message_visible_to_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="visible_to_sender",
        ),
    ]
