# Generated by Django 5.2.3 on 2025-08-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0010_block_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="created_at",
        ),
    ]
