# Generated by Django 5.2.3 on 2025-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0011_remove_block_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sent_after_block",
            field=models.BooleanField(default=False),
        ),
    ]
