# Generated by Django 5.2.3 on 2025-08-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0012_message_sent_after_block"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="sent_after_block",
            new_name="sent_during_block",
        ),
    ]
