# Generated by Django 5.2.3 on 2025-08-19 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0013_rename_sent_after_block_message_sent_during_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
