# Generated by Django 5.2.3 on 2025-08-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0014_block_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="visible_to_receiver",
        ),
    ]
