# Generated by Django 5.2.3 on 2025-08-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0015_remove_message_visible_to_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
    ]
