# Generated by Django 5.2.3 on 2025-08-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0016_remove_message_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="created_at",
        ),
    ]
