# Generated by Django 5.2.3 on 2025-08-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0017_remove_block_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="disappear_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="disappear_option",
            field=models.CharField(
                choices=[("off", "Off"), ("24h", "24 Hours"), ("7d", "7 Days")],
                default="off",
                max_length=10,
            ),
        ),
    ]
