# Generated by Django 5.2.3 on 2025-08-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0018_message_disappear_at_message_disappear_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="disappear_option",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("24h", "24 Hours"),
                    ("7d", "7 Days"),
                    ("1minute", "1 Minute"),
                ],
                default="off",
                max_length=10,
            ),
        ),
    ]
