# Generated by Django 5.2.3 on 2025-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0019_alter_message_disappear_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
