# Generated by Django 5.2.3 on 2025-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0020_message_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="disappearing_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
