# Generated by Django 5.2.3 on 2025-08-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0024_myuser_disappearing_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="disappearing_enabled",
        ),
    ]
