# Generated by Django 5.2.3 on 2025-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0025_remove_myuser_disappearing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="disappearing_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
