# Generated by Django 5.2.3 on 2025-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0026_myuser_disappearing_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="encryption_content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
