# Generated by Django 5.2.3 on 2025-09-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0027_message_encryption_content_alter_message_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="encryption_content",
            new_name="encrypted_content",
        ),
    ]
